apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-project
  labels:
    app: web-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-project
  template:
    metadata:
      labels:
        app: web-project
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: web-project
        image: tharcisiomendonca/web-project
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: web-project
  labels:
    app: web-project
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: web-project